-- ============================================================
-- TASKY — Supabase schema
-- Paste this into the Supabase SQL editor and run it.
--
-- To update the required app version (force users to git pull):
--   INSERT INTO app_version (version, notes)
--   VALUES ('1.x.x', 'Descripción del cambio');
-- ============================================================

CREATE TABLE IF NOT EXISTS users (
    username     TEXT PRIMARY KEY,
    display_name TEXT NOT NULL,
    email        TEXT UNIQUE
);

-- Para proyectos ya existentes (creados antes del login con email/contraseña):
--   ALTER TABLE users ADD COLUMN email TEXT UNIQUE;

CREATE TABLE IF NOT EXISTS projects (
    name  TEXT PRIMARY KEY,
    color TEXT NOT NULL DEFAULT '#00FFFF'
);

CREATE TABLE IF NOT EXISTS tasks (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project     TEXT    NOT NULL REFERENCES projects(name) ON UPDATE CASCADE ON DELETE CASCADE,
    task        TEXT    NOT NULL,
    priority    TEXT    NOT NULL DEFAULT '2. MEDIUM',
    status      TEXT    NOT NULL DEFAULT 'TO DO',
    notes       TEXT,
    sort_order  INTEGER NOT NULL DEFAULT 0,
    assigned_to TEXT    REFERENCES users(username) ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS sub_tasks (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id    BIGINT  NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,
    task       TEXT    NOT NULL,
    status     TEXT    NOT NULL DEFAULT 'TO DO',
    notes      TEXT,
    sort_order INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS project_logs (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project  TEXT NOT NULL REFERENCES projects(name) ON UPDATE CASCADE ON DELETE CASCADE,
    log_date TEXT NOT NULL,
    title    TEXT NOT NULL DEFAULT 'Milestone',
    notes    TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS app_version (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version    TEXT NOT NULL,
    notes      TEXT,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Versión inicial
INSERT INTO app_version (version, notes)
VALUES ('1.0.0', 'Versión inicial');
